name: cicd-demo
on:
  push:
    branches:
      - '*'

jobs:
  build-job:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: 'Start build job'
        run: |
          echo "Starting the build job."
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: 'Setup Java JDK'
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: 'temurin'
      - name: 'Check Java Version'
        run: |
          java --version
      - name: 'Asseble JAR'
        run: |
          ./gradlew assemble
      - name: 'Get Version Number'
        run: |
          echo "VERSION=$(./gradlew properties -q | grep "version:" |
          awk '{print $2}')" >> $GITHUB_ENV
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: 'cicd-demo-${{env.VERSION}}-all.jar'
          path: build/libs/*-all.jar
      - name: 'Run Tests'
        run: |
          ./gradlew test