name: cicd-demo
on:
  push:
    branches:
      - '*'

jobs:
  build-job:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: 'Start build job'
        run: |
          echo "Starting the build job."
      - name: Checkout
        uses: actions/checkout@v2.5.0
